export type TransactionType = 'income' | 'expense';

export interface User {
  id?: string;
  name: string;
  email: string;
  avatarUrl?: string;
  baseSalary?: number;
  salaryPaymentDay?: number;
  salaryAdvanceDay?: number;
  salaryAdvancePercent?: number;
  salaryAdvanceValue?: number;
  valeDeductions?: { id: string; name: string; value: string; type: '%' | 'R$' }[];
  valeExemptFromDiscounts?: boolean;
  salaryExemptFromDiscounts?: boolean;
  twoFactorEnabled?: boolean;
  twoFactorSecret?: string | null;
  subscription?: {
    plan: 'starter' | 'pro' | 'family';
    status: 'active' | 'canceled' | 'past_due' | 'pending_payment' | 'refunded';
    billingCycle: 'monthly' | 'annual';
    nextBillingDate?: string;
    installments?: number;
    asaasCustomerId?: string;
    asaasSubscriptionId?: string;
    asaasPaymentId?: string; // ID do último pagamento para estorno
    couponUsed?: string;
    startDate?: string;
    autoRenew?: boolean;
  };
  paymentMethodDetails?: {
    last4: string;
    holder: string;
    expiry: string;
    brand?: string;
  };
  familyGroupId?: string;
  familyRole?: 'owner' | 'member';
  isAdmin?: boolean;
  cpf?: string;
  birthDate?: string;
  address?: {
    cep: string;
    street: string;
    number: string;
    complement?: string;
    neighborhood: string;
    city: string;
    state: string;
  };
  dailyConnectionCredits?: {
    date: string; // YYYY-MM-DD
    count: number;
  };
  createdAt?: string;
  hasSeenProTutorial?: boolean;
  connectionLogs?: ConnectionLog[];
}

export interface ConnectionLog {
  id: string;
  os: string;
  browser: string;
  ip: string;
  location: string;
  device: string;
  timestamp: string;
  isCurrent?: boolean;
}

export interface FamilyGroup {
  id: string;
  ownerId: string;
  plan: 'pro' | 'family';
  members: string[]; // User IDs
  invites: {
    token: string;
    createdAt: string;
    status: 'pending' | 'accepted';
    email?: string;
  }[];
}

export interface Member {
  id: string;
  name: string;
  avatarUrl?: string;
  role: 'admin' | 'member';
}

export interface FamilyGoal {
  id: string;
  title: string;
  targetAmount: number;
  currentAmount: number;
  deadline?: string;
  icon?: string;
}

export interface Subscription {
  id: string;
  userId: string;
  name: string;
  amount: number;
  billingCycle: 'monthly' | 'yearly';
  status: 'active' | 'canceled';
  lastPaymentDate?: string;
  category: string;
  provider?: string;
  paidMonths?: string[]; // Meses em que foi marcada como paga (YYYY-MM), não soma no custo mensal
}

export interface WaitlistEntry {
  id?: string;
  name: string;
  email: string;
  phone?: string;
  goal?: string;
  source?: string;
  createdAt: string;
}

export interface Transaction {
  id: string;
  memberId?: string;

  date: string; // YYYY-MM-DD
  description: string;
  amount: number;
  category: string;

  type: TransactionType; // (confirme se seu enum aceita 'income' | 'expense' ou ajuste no backend)
  status: 'completed' | 'pending';

  // Optional flags
  importSource?: string; // e.g. "klavi", "pluggy" - identifies auto-imported transactions
  needsApproval?: boolean;
  ignored?: boolean;
  isSubscription?: boolean;
  paidSubscriptionId?: string;

  providerId?: string; // legacy field, importSource preferred
  providerItemId?: string;

  // Invoice fields (cartão)
  invoiceDate?: string; // Invoice month this transaction belongs to (YYYY-MM-01)
  invoiceDueDate?: string; // Actual due date of the invoice (YYYY-MM-DD)
  dueDate?: string; // alias for invoiceDueDate

  // Account fields
  accountId?: string;
  accountType?: string; // 'CHECKING_ACCOUNT', 'CREDIT_CARD', 'SAVINGS_ACCOUNT'
  isInvestment?: boolean;

  // Credit card specific fields
  cardId?: string;
  cardName?: string;
  installmentNumber?: number;
  totalInstallments?: number;
  isProjected?: boolean; // True for future installments generated by sync

  // ✅ EXTRA (opcionais, recomendados para "bater com o banco" e debug)
  invoiceMonthKey?: string; // "YYYY-MM" (canônico do mês da fatura, facilita filtro)
  pluggyBillId?: string | null; // Bill/Fatura id do Pluggy (quando existir)
  invoiceSource?: 'pluggy_billId' | 'pluggy_month_match' | 'rule_fallback' | string; // origem do cálculo
  pluggyRaw?: any; // JSON bruto/sanitizado da transação (para inspeção no modal)
}


export interface Reminder {
  id: string;
  memberId?: string;
  description: string;
  amount: number;
  dueDate: string;
  category: string;
  type?: TransactionType;
  isRecurring: boolean;
  frequency?: 'monthly' | 'weekly' | 'yearly';
}

export interface Investment {
  id: string;
  memberId?: string;
  name: string;
  icon: string;
  color: string;
  targetAmount: number;
  currentAmount: number;
  createdAt: string;
  deadline?: string;
}

export interface DashboardStats {
  totalBalance: number;
  totalIncome: number;
  totalExpense: number;
  monthlySavings: number;
  creditCardSpending?: number;
}

export interface AIAnalysisResult {
  summary: string;
  insights: string[];
  recommendations: string[];
}

export interface AIParsedTransaction {
  description: string;
  amount: number;
  category: string;
  date: string;
  type: TransactionType;
  installments?: number;
  isSubscription?: boolean;
}

export type ToastType = 'success' | 'error' | 'info' | 'warning';

export interface ToastMessage {
  id: string;
  type: ToastType;
  title: string;
  message?: string;
}

export interface Budget {
  id: string;
  memberId?: string;
  name?: string;
  category: string;
  limitAmount: number;
  month: string;
  alertThreshold: number;
}

export interface ConnectedTransactionPreview {
  id: string;
  description: string;
  amount: number;
  date: string;
  type: TransactionType;
  category?: string;
  installments?: {
    number?: number;
    total?: number;
  };
  currency?: string;
}

export interface ProviderBill {
  id: string;
  dueDate: string;
  totalAmount: number;
  totalAmountCurrencyCode?: string;
  minimumPaymentAmount?: number;
  allowsInstallments?: boolean;
  financeCharges?: any[];
  balanceCloseDate?: string;
  state?: 'OPEN' | 'CLOSED' | 'FUTURE'; // Bill state from Pluggy
  paidAmount?: number;
}

export interface ConnectedAccount {
  id: string;
  itemId: string;
  name: string;
  type?: string;
  subtype?: string;
  // Friendly account type classification
  accountTypeName?: string; // 'Conta Corrente', 'Poupança', 'Cartão de Crédito'
  isCredit?: boolean;
  isSavings?: boolean;
  isChecking?: boolean;
  institution?: string;
  balance?: number;
  currency?: string;
  lastUpdated?: string;
  previewTransactions?: ConnectedTransactionPreview[];
  // Credit card specific
  creditLimit?: number;
  availableCreditLimit?: number;
  usedCreditLimit?: number;
  manualCreditLimit?: number; // User-defined limit when API doesn't provide it
  brand?: string;
  balanceCloseDate?: string;
  balanceDueDate?: string;
  closingDay?: number;
  dueDay?: number;
  minimumPayment?: number;
  bills?: ProviderBill[];
  connectionMode?: 'AUTO' | 'MANUAL';
  initialBalance?: number;

  // Current bill info (for display)
  currentBill?: {
    dueDate?: string;
    totalAmount?: number;
    state?: string;
    paidAmount?: number;
    minimumPayment?: number;
  };
  // Bank account specific
  accountNumber?: string;
  bankNumber?: string;
  branchNumber?: string;
  transferNumber?: string;
  // Sync tracking
  connectedAt?: string;   // ISO timestamp of first connection
  lastSyncedAt?: string;  // ISO timestamp of last sync
}

export interface AppNotification {
  id: string;
  type: 'system' | 'alert' | 'update' | 'budget_warning' | 'budget_danger';
  title: string;
  message: string;
  date: string;
  read: boolean;
  archived?: boolean;
}

export interface Coupon {
  id: string;
  code: string;
  type: 'percentage' | 'fixed' | 'progressive';
  value: number; // Percentage (0-100) or Fixed Amount (for non-progressive)
  isActive: boolean;
  maxUses?: number; // Optional limit
  currentUses: number;
  expirationDate?: string; // ISO Date
  createdAt: string;
  // Progressive discount: different discount per billing month
  // Example: [{month: 1, discount: 100, discountType: 'percentage'}, {month: 2, discount: 50, discountType: 'fixed'}]
  progressiveDiscounts?: { month: number; discount: number; discountType?: 'percentage' | 'fixed' }[];
  partnership?: {
    partnerName: string;
    commissionType: 'percentage' | 'fixed';
    commissionValue: number;
    accumulatedCommission: number;
    partnerPix?: string;
  };
}

export interface PromoPopup {
  id: string;
  title: string;
  message: string;
  imageUrl?: string | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  type: 'info' | 'promo' | 'update';
  dismissible?: boolean;
  expiresAt?: string;
  createdAt: string;
  dismissed?: boolean;
}

export interface SystemSettings {
  metaPixelId?: string;
}
